#include "pwm.h"

#include "main.h"
#include "tim.h"

extern "C" {

/* TIM2 is expected to be generated by CubeMX as PWM on CH1/CH2. */
extern TIM_HandleTypeDef htim2;
void MX_TIM2_Init(void);

void PWM_Init(void)
{
  MX_TIM2_Init();
  (void)HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);
  (void)HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_2);
}

void PWM_SetCompare1(uint16_t compare)
{
  __HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, compare);
}

void PWM_SetCompare2(uint16_t compare)
{
  __HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_2, compare);
}

}  // extern "C"

